import React, { useState } from "react"; 
import { addCarExtra } from "../services/CarExtraService"; // Import the addCarExtra function from the service
import { toast } from "react-toastify"; // For notifications
import "react-toastify/dist/ReactToastify.css"; // Import Toastify styles
import "./AddCarExtra.css"; 

const AddCarExtra = () => {
  // State to hold form data
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [price, setPrice] = useState("");
  const [loading, setLoading] = useState(false); // Loading state

  // Handle form submission
  const handleSubmit = async (e) => {
    e.preventDefault();

    // Basic validation
    if (!name || !description || !price) {
      toast.error("All fields are required!");
      return;
    }

    setLoading(true); // Set loading state while making the API call

    const carExtraDTO = {
      extraId: 0, // ID will be autogenerated by the backend, so this is just a placeholder
      name,
      description,
      price: parseFloat(price), // Ensure price is a number
    };

    try {
      const response = await addCarExtra(carExtraDTO);
      if (response) {
        /*toast.success("Car extra added successfully!");*/
        // Clear form or redirect to car extra list or another page
        setName("");
        setDescription("");
        setPrice("");
      }
    } catch (error) {
      toast.error("Failed to add car extra. Please try again.");
    } finally {
      setLoading(false); // Reset loading state
    }
  };

  return (
    <div className="add-car-extra-container">
      <h2>Add New Car Extra</h2>
      <form onSubmit={handleSubmit}>
        {/* Name */}
        <div className="form-group">
          <label htmlFor="name">Name</label>
          <input
            type="text"
            id="name"
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="Enter car extra name"
          />
        </div>

        {/* Description */}
        <div className="form-group">
          <label htmlFor="description">Description</label>
          <input
            type="text"
            id="description"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="Enter car extra description"
          />
        </div>

        {/* Price */}
        <div className="form-group">
          <label htmlFor="price">Price</label>
          <input
            type="number"
            id="price"
            value={price}
            onChange={(e) => setPrice(e.target.value)}
            placeholder="Enter price"
          />
        </div>

        {/* Submit Button */}
        <button type="submit" disabled={loading}>
          {loading ? "Adding..." : "Add Car Extra"}
        </button>
      </form>
    </div>
  );
};

export default AddCarExtra;
